import React from "react";
import { motion } from "motion/react";
const CardHomeSection = () => {
  const highLights = [
    "AI Generated Code",
    "Fully Responsive Layouts",
    "Production Ready Output",
  ];

  const hilightDescriptions = [
  "Clean, modern code generated by AI — no boilerplate, no bloat. Just production-quality HTML, CSS, and JS tailored to your design.",
  "Every website looks perfect on any screen. Mobile, tablet, or desktop — layouts that adapt automatically without extra effort.",
  "Ship faster with output that's ready to deploy. Optimized structure, clean markup, and scalable architecture out of the box.",
];

  return (
    <section className="max-w-7xl mx-auto px-6 pb-32">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
        {highLights.map((h, i) => (
          <motion.div
           key={i}
           initial={{ opacity: 0, y: 40 }}
           whileInView={{ opacity: 1, y: 0 }}
           className="rounded-2xl bg-white/5 border border-white/10 p-8"
           >
            <h1 className="text-xl font-semibold mb-3">{h}</h1>
            <p className="text-sm text-zinc-400">
              {hilightDescriptions[i]}
            </p>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default CardHomeSection;
